### ISSUE TITLE
Score Integration

### ISSUE THREAD

**Issue by vinnnnncy** [Charles-Xie/CQL#5]
Hi, Thx for the code release. Can u tell me where is the part of 'hard/soft score integration' in the provided code?

**Comment by Charles-Xie** [comment]
Thanks for your attention to this work!
Actually, score integration is not in this codebase, as we find the version without this trick already achieves a similar performance reported in the paper.
Score integration is a small trick that has only a slight improvement on the baseline. That's why we keep its detail in the supplementary material and only mentioned it briefly in the main paper.
if you want to have a try, you can refer to the similar implementation in [rankseg](https://github.com/openseg-group/RankSeg) for hard integration, while soft integration is simply multiplication between image-level and instance-level score.
